# Generated by Django 4.2.6 on 2023-10-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='naem',
            new_name='name',
        ),
    ]
